### ISSUE TITLE
is there any way to keep hight of tile same or increase the hight of tile when mobile breakpoint is reached.

### ISSUE THREAD

**Issue by shyambhiogade** [tiberiuzuld/angular-gridster2#334]
@tiberiuzuld , 
i noticed that when breakpoint is reached it also reduces the height of my tile, 

before breakpoint
![image](https://user-images.githubusercontent.com/10468130/39933908-1093dbfc-54f9-11e8-87df-125e5c0468f6.png)

after breakpoint, notice the cropped tile area

![image](https://user-images.githubusercontent.com/10468130/39933947-30977db4-54f9-11e8-8b2b-715981aa3c7f.png)

is it possible to maintain or increase the height of tile when breakpoint is reached.

**Comment by tiberiuzuld** [comment]
https://tiberiuzuld.github.io/angular-gridster2/gridTypes

**Comment by shyambhiogade** [comment]
i need to use the verticalScroll type, i can not use the fixed type grid.

**Comment by tiberiuzuld** [comment]
Ok seems that keepFixedHeightInMobile is no longer used in the library. Seems I removed it from the code with the css grid refactoring try.
Will try to have it fixed this week.

**Comment by tiberiuzuld** [comment]
Fixed in v6.0.3
You can use now `keepFixedHeightInMobile` to set what size you want in mobile.

Thanks

**Comment by shyambhiogade** [comment]
hi, i tried using the latest library, 
i have verticalScroll grid type set and when in increase the breakpoint, it doesnt main the height, please see below image,

![zoom_0](https://user-images.githubusercontent.com/10468130/39980985-50746c9e-5703-11e8-907d-e34e9bb7f200.gif)

**Comment by tiberiuzuld** [comment]
Hi @shyambhiogade ,
The property `fixedRowHeight` sets the height of the items in mobile view if you use `keepFixedHeightInMobile`

**Comment by julsette** [comment]
Hi @tiberiuzuld ,
I still cannot see `keepFixedHeightInMobile` work.
I tested it in my application with the latest version installed and also in your demo page and this is what happens:
![image](https://user-images.githubusercontent.com/22366536/40105016-15e2f168-58f2-11e8-9caa-499593e7b6d2.png)

It does not keep the height of the items as it used to before.
I was using v4.2.0 before trying to update, and it did work just fine without specifying any other property, it just kept the same height the items occupied when in full screen after reaching the mobile breakpoint, only by setting the `keepFixedHeightInMobile` flag to true.

I'm waiting for a fix before updating permanently because I need this property to work.

**Comment by tiberiuzuld** [comment]
Hi @julsette ,
Yes before the height was not removed from items style when moving from a above the `mobileBreakpoint` to lower.(from my point of view this was a bug) But on page refresh was applied a percentage of height from what I remember. https://github.com/tiberiuzuld/angular-gridster2/blob/4.x/src/lib/gridsterItem.component.ts#L82
Also even then in 4.x the `keepFixedHeightInMobile` will seet the height of property `fixedRowHeight`.

But if you still want that functionality maybe will think of something.

**Comment by tiberiuzuld** [comment]
@shyambhiogade 
1. if the dashboard loads directly in mobile view there is no height to keep.
2. making extra option on widgets to keep a min height in px is not usable and complex to use.
3. the height you mention depends on the `gridType` and screen dimensions.

The only thing I can do easily is to make mobile view behave like `gridType: 'scrollVertical'` with only one column. In `scrollVertical` the width of the column will be equal to height of a row.

But not every one will like that, will think about it and how to implement it.

**Comment by julsette** [comment]
@tiberiuzuld  Thanks for your answer!
It's strange because even after a page refresh the items in my dialog keep the same height as they did before.
The reason why I needed an input like this is that there are cases in which a common height for all the items does not look great.
For example, this is a sample dashboard with three items and the `keepFixedHeight` I was using in v4
![image](https://user-images.githubusercontent.com/22366536/40119801-e4f513a2-591d-11e8-9237-ae68a31ed355.png)


With `keepFixedHeight` in 6.x it would be something like this:
![image](https://user-images.githubusercontent.com/22366536/40119835-0110bed8-591e-11e8-8349-8053ca258ad6.png)

In this case the teal item is just fine with that height but the other one needs to have a different height to be usable/visible in a decent way.
Setting the `fixedRowHeight` property, if I understood correctly, I'd have that height fixed for each item. But in my case that would not be good considered that the teal item would be too high and would not look good.  (I hope I explained my issue well)

**Comment by tiberiuzuld** [comment]
@julsette hmm interesting, ok maybe is something I missed in v4, will have a look to try to have the same effect.

**Comment by tiberiuzuld** [comment]
Ok I think I have a fix in v6.0.4

Now with `keepFixedHeightInMobile` will multiply `fixedRowHeight` by the number of rows the item has. This is the thing I missed when making changes.

Now without `fixedRowHeight` will also multiply the item.rows with half of the column width.

Please confirm that works as before.

**Comment by tiberiuzuld** [comment]
Glad to hear, thanks for the confirmation.

**Comment by lefoulkrod** [comment]
Are there settings that would make each widget height set to auto so it takes up as much height as it content?

**Comment by menamostafa** [comment]
@lefoulkrod @tiberiuzuld 
I also set the gridster-item's height to auto to able to show all the gridster-item's content without scrolling but I got issue where the gridster-item's height exceed the gridster height, How could I display the gridster-item without scrolling or how to fix this issue?

These are the gridster options: 

`export const GridsterOptions = {
    gridType: GridType.ScrollVertical,
   compactType: CompactType.CompactUpAndLeft,
    margin: 20,
    useTransformPositioning: true,
    mobileBreakpoint: 500,
    setGridSize: true,
    keepFixedHeightInMobile: false,
    keepFixedWidthInMobile: false,
    scrollSensitivity: 10,
    scrollSpeed: 20,
    draggable: {
        enabled: true,
    },
    resizable: {
        enabled: true,
    },
    swap: true,
    pushItems: true,
    disablePushOnDrag: false,
    disablePushOnResize: false,
    pushDirections: { north: true, east: true, south: true, west: true },
    pushResizeItems: true,
    displayGrid: DisplayGrid.OnDragAndResize,
    disableWindowResize: false,
    disableWarnings: false,
    scrollToNewItems: false
};`
